### ISSUE TITLE
Compatibilzar regras de Lint para o ES-LINT

### ISSUE THREAD

**Issue by alvarocamillont** [po-ui/po-tslint#1]
Bom dia!

Conforme informações da equipe do ts-lint, eles irão ser incorporados ao es-lint e o projeto será desativado. (https://eslint.org/blog/2019/01/future-typescript-eslint)
É preciso atualizar o lint e verificar se ele funciona corretamente com a ultima versão do es-lint.

**Comment by jhosefmarks** [comment]
Bom dia @alvarocamillont,

Vamos adicionar sua sugestão ao backlog, vamos priorizar conforme nossa demanda.
